#Makefile: Este archivo compila y ejecuta su código al escribir make en consola en sistemas UNIX

all: compilar ejecutar

compilar: 
	@gcc -o practico3 main.c tree.c pregunta_1.c pregunta_2.c pregunta_3.c pregunta_4.c pregunta_5.c

ejecutar: compilar
	@./practico3 data.csv